// Scripted scenarios for the Enterprise AI sandbox. Every answer is fictional
// sample data, labelled as such in the UI.
// Display strings are translated at render time with tx(); keywords and SQL stay in English.
export const DATASETS = [
  {
    id: "finance",
    label: "Finance",
    systems: ["SAP S/4HANA", "SAP ECC archive (2009-2019)", "Salesforce"],
    questions: [
      {
        q: "Which customers are paying late this quarter, compared with last year?",
        keywords: ["late", "pay", "overdue", "dso", "customers", "receivable"],
        tables: ["BSID (open items)", "KNA1 (customers)", "archived BSAD 2019-2023"],
        sql: "SELECT c.name, AVG(days_late) AS avg_days_late\nFROM open_items o JOIN customers c USING (customer_id)\nWHERE quarter = CURRENT_QUARTER\nGROUP BY c.name ORDER BY avg_days_late DESC LIMIT 4;",
        columns: ["Customer", "Avg. days late", "Last year"],
        rows: [["Northwind Traders", 38, 21], ["Contoso GmbH", 31, 29], ["Fabrikam Ltd", 27, 12], ["Tailspin S.A.", 22, 25]],
        answer: "Four customers average more than 20 days late this quarter. Northwind Traders and Fabrikam Ltd have worsened the most since last year; Tailspin S.A. has improved.",
        pii: ["Contact name", "Bank account"],
      },
      {
        q: "How much did we spend with our top suppliers over the last five years?",
        keywords: ["spend", "supplier", "vendor", "procurement", "purchase"],
        tables: ["EKKO/EKPO (purchase orders)", "LFA1 (vendors)", "archived purchasing 2019-2021"],
        sql: "SELECT v.name, SUM(net_value_usd) AS spend\nFROM purchase_orders p JOIN vendors v USING (vendor_id)\nWHERE doc_date >= CURRENT_DATE - INTERVAL '5 years'\nGROUP BY v.name ORDER BY spend DESC LIMIT 4;",
        columns: ["Supplier", "5-year spend (USD m)", "Share"],
        rows: [["Globex Components", 48.2, "18%"], ["Initech Logistics", 31.7, "12%"], ["Umbrella Packaging", 22.4, "8%"], ["Stark Industrial", 19.9, "7%"]],
        answer: "The top four suppliers account for 45% of spend over five years. Two of those five years only exist in the archived ECC system, and the answer includes them.",
        pii: ["Bank account"],
      },
      {
        q: "Summarise our revenue by region for the last three years.",
        keywords: ["revenue", "region", "sales", "trend", "growth"],
        tables: ["ACDOCA (universal journal)", "archived FAGLFLEXA 2019-2021"],
        sql: "SELECT region, fiscal_year, SUM(revenue_usd)\nFROM journal_entries\nWHERE account_class = 'REVENUE' AND fiscal_year >= 2023\nGROUP BY region, fiscal_year;",
        columns: ["Region", "2023", "2024", "2025"],
        rows: [["Americas", 412, 438, 471], ["EMEA", 305, 322, 349], ["APAC", 188, 214, 251], ["Middle East & Africa", 64, 71, 83]],
        answer: "Revenue grew in every region; APAC grew fastest at 34% over three years. Figures in USD millions.",
        pii: [],
      },
    ],
  },
  {
    id: "healthcare",
    label: "Healthcare",
    systems: ["Epic (live EHR)", "Retired Cerner archive", "Claims warehouse"],
    questions: [
      {
        q: "Which patients with diabetes missed a follow-up in the last 6 months?",
        keywords: ["patient", "diabetes", "follow", "missed", "appointment", "care gap"],
        tables: ["encounters", "problem_list", "archived Cerner visits 2012-2020"],
        sql: "SELECT patient_id, last_visit, days_overdue\nFROM care_gaps\nWHERE condition = 'E11' AND days_overdue > 0\nORDER BY days_overdue DESC LIMIT 4;",
        columns: ["Patient", "Last visit", "Days overdue"],
        rows: [["Patient 4821", "2025-11-02", 142], ["Patient 1177", "2025-12-15", 98], ["Patient 9034", "2026-01-20", 61], ["Patient 2268", "2026-02-11", 40]],
        answer: "212 patients with type 2 diabetes are overdue for a follow-up. The four longest gaps are shown; history from the retired EHR is included so earlier visits aren't missed.",
        pii: ["Name", "Date of birth", "Address"],
      },
      {
        q: "What is our 30-day readmission rate by department?",
        keywords: ["readmission", "department", "rate", "30-day", "discharge"],
        tables: ["admissions", "discharges", "departments"],
        sql: "SELECT dept, ROUND(100.0 * readmitted_30d / discharges, 1)\nFROM readmission_summary WHERE year = 2025;",
        columns: ["Department", "Readmission rate", "National benchmark"],
        rows: [["Cardiology", "14.2%", "15.1%"], ["Orthopaedics", "6.8%", "7.9%"], ["Pulmonology", "17.9%", "16.4%"], ["General medicine", "12.1%", "13.0%"]],
        answer: "Pulmonology is the only department above the national benchmark. The others are 0.9 to 1.1 points better.",
        pii: [],
      },
      {
        q: "Find every record we hold for one patient for a records request.",
        keywords: ["records", "request", "dsar", "all data", "everything", "hipaa"],
        tables: ["Epic", "Cerner archive", "claims", "scanned documents"],
        sql: "CALL find_subject(identifier => :mrn, scope => 'ALL_SYSTEMS');",
        columns: ["System", "Records found", "Oldest"],
        rows: [["Epic (live)", 184, "2020"], ["Cerner archive", 431, "2008"], ["Claims warehouse", 96, "2011"], ["Scanned documents", 27, "2006"]],
        answer: "738 records across four systems, the oldest from 2006. They can be exported as one package with an audit trail.",
        pii: ["Name", "Date of birth", "Address", "Diagnosis"],
      },
    ],
  },
  {
    id: "manufacturing",
    label: "Manufacturing",
    systems: ["MES (plant floor)", "Oracle EBS", "Quality archive"],
    questions: [
      {
        q: "Which production lines had the most unplanned downtime last month?",
        keywords: ["downtime", "line", "production", "oee", "unplanned", "stoppage"],
        tables: ["machine_events", "lines", "shifts"],
        sql: "SELECT line, SUM(minutes) AS downtime\nFROM machine_events WHERE type = 'UNPLANNED' AND month = LAST_MONTH\nGROUP BY line ORDER BY downtime DESC LIMIT 4;",
        columns: ["Line", "Downtime (hours)", "Top cause"],
        rows: [["Stuttgart L3", 41, "Spindle overheating"], ["Pune L1", 33, "Material shortage"], ["Monterrey L2", 26, "Tool change"], ["Ohio L4", 19, "Sensor fault"]],
        answer: "Stuttgart L3 lost 41 hours, mostly to spindle overheating, the same cause as two quarters ago in the quality archive.",
        pii: [],
      },
      {
        q: "Trace every product shipped with components from supplier batch B-7731.",
        keywords: ["trace", "batch", "recall", "lot", "shipped", "genealogy"],
        tables: ["lot_genealogy", "shipments", "archived quality records"],
        sql: "WITH RECURSIVE tree AS (...) SELECT serial, customer, ship_date\nFROM tree JOIN shipments USING (serial);",
        columns: ["Serial", "Customer", "Shipped"],
        rows: [["SX-20-114873", "Globex (DE)", "2025-09-12"], ["SX-20-114901", "Initech (US)", "2025-09-14"], ["SX-20-115002", "Umbrella (JP)", "2025-09-20"], ["SX-20-115117", "Hooli (IN)", "2025-10-02"]],
        answer: "1,284 units in 9 countries contain parts from batch B-7731. The full list is ready to hand to the recall team.",
        pii: ["Customer contact"],
      },
      {
        q: "Compare scrap rates across plants this year.",
        keywords: ["scrap", "waste", "yield", "plants", "compare", "quality"],
        tables: ["quality_inspections", "plants"],
        sql: "SELECT plant, ROUND(100.0 * scrapped / produced, 2) FROM yield_by_plant WHERE year = 2026;",
        columns: ["Plant", "Scrap rate", "Change vs. 2025"],
        rows: [["Stuttgart", "1.8%", "-0.4"], ["Pune", "2.6%", "-0.9"], ["Monterrey", "2.1%", "+0.2"], ["Ohio", "1.5%", "-0.1"]],
        answer: "Ohio has the lowest scrap rate; Pune improved most. Monterrey is the only plant that got worse.",
        pii: [],
      },
    ],
  },
  {
    id: "pharma",
    label: "Pharma",
    systems: ["Clinical trial systems", "Regulatory archive", "Lab (LIMS)"],
    questions: [
      {
        q: "Which trial sites are behind on enrolment for study SX-204?",
        keywords: ["trial", "site", "enrolment", "enrollment", "recruit", "study"],
        tables: ["ctms_sites", "enrolment_events"],
        sql: "SELECT site, enrolled, target FROM enrolment_status WHERE study = 'SX-204' AND enrolled < target;",
        columns: ["Site", "Enrolled", "Target"],
        rows: [["Berlin Charité", 18, 30], ["São Paulo", 22, 30], ["Bengaluru", 25, 30], ["Boston", 27, 30]],
        answer: "Four of 12 sites are behind; Berlin is furthest at 60% of target.",
        pii: ["Participant ID"],
      },
      {
        q: "Summarise adverse events reported for compound SX-11 across all studies.",
        keywords: ["adverse", "event", "safety", "compound", "side effect"],
        tables: ["safety_db", "archived studies 2014-2019"],
        sql: "SELECT meddra_term, COUNT(*) FROM adverse_events WHERE compound = 'SX-11' GROUP BY meddra_term ORDER BY 2 DESC LIMIT 4;",
        columns: ["Event (MedDRA)", "Reports", "Serious"],
        rows: [["Headache", 212, 3], ["Nausea", 168, 1], ["Fatigue", 97, 0], ["Elevated ALT", 41, 6]],
        answer: "Headache and nausea are most common; elevated ALT has the most serious reports and is flagged for the safety review. Includes studies retired to the archive.",
        pii: ["Participant ID", "Date of birth"],
      },
      {
        q: "Which regulatory submissions reference batch data older than 10 years?",
        keywords: ["regulatory", "submission", "batch", "older", "gxp", "fda", "ema"],
        tables: ["regulatory_archive", "lims_batches"],
        sql: "SELECT submission, batch, batch_year FROM submission_refs WHERE batch_year < 2016;",
        columns: ["Submission", "Batch", "Year"],
        rows: [["EMA-2021-0457", "LB-2014-117", 2014], ["FDA-NDA-21-883", "LB-2012-044", 2012], ["PMDA-2022-061", "LB-2015-209", 2015], ["CDSCO-2023-19", "LB-2013-331", 2013]],
        answer: "Seven submissions to four regulators reference batches older than 10 years. All the batch records are preserved and retrievable.",
        pii: [],
      },
    ],
  },
];

export const ROLES = [
  { id: "analyst", label: "Analyst", rule: "Personal data is masked; aggregates and business fields are visible." },
  { id: "executive", label: "Executive", rule: "Summaries only. Row-level personal data is never returned." },
  { id: "auditor", label: "Auditor", rule: "Full lineage and the generated query are shown; personal data is tokenised." },
];

export const DEFAULT_DATASET = { "ai-healthcare": "healthcare", "eai-pharma": "pharma" };
